### ISSUE TITLE
Motion Capture - Body doesn't move

### ISSUE THREAD

**Issue by hangeddeyvi** [endink/Mediapipe4u-plugin#114] opened 2023-09-23 00:39 UTC
### MediaPipe4U Version

20230829

### UE Version

5.2.x

### UnrealEngine Type

Compiled From Source Code

### What happened?

Hello,

Motion capture issue. Body doesn't move, neighter with webcam nor with video. Tried both with UE 5.1 and 5.2 with the respective plugins. 

I see in the log, which constantly repeats:

LogMediaPipe: Display: Start prepare mediapipe joint mapping  (HeadSolver).
LogMediaPipe: Error: Bone 'thigh_l' is not a valid compact pose bone. (UJointMapperBase::GetBoneTransformFromPose)
LogMediaPipe: Warning: The orientation of the body cannot be determined, possibly necessary bone mapping missed. (UJointMapperBase::CalibrateJoints)

What may be the issue? How can I solve it?

Thank you

**Comment by endink** [comment] 2023-09-23 02:07
If bone changed, maybe the LOD changed.

**Comment by hangeddeyvi** [comment] 2023-09-23 09:49
Yes, changing the LOD level of the character solved that issue, but the body still does not move

**Comment by endink** [comment] 2023-09-23 10:40
LoD propeety of the animation blueprint node can be found in details pannel.   

Its a UE acknowledge, not a M4U special settings, I only log it as warning.    

I think we can close this issue.

**Comment by hangeddeyvi** [comment] 2023-09-23 11:01
Yes, it has worked now, thanks

**Comment by endink** [comment] 2023-09-23 11:04
Glad to hear about this !

**Closed by endink** 2023-09-23 11:04 UTC

**Comment by jossevessies** [comment] 2023-11-09 10:30
Dear Endlink,

Thanks for creating this amazing tool.

I am though having the same issue as hangeddeyvi, in the demo-file.

LogMediaPipe: Display: Start prepare mediapipe joint mapping (HeadSolver).
LogMediaPipe: Error: Bone 'thigh_l' is not a valid compact pose bone. (UJointMapperBase::GetBoneTransformFromPose)
LogMediaPipe: Warning: The orientation of the body cannot be determined, possibly necessary bone mapping missed. (UJointMapperBase::CalibrateJoints)


I tried finding the lod settings, there are a couple.
Eventually I went into the details of 'skm_quinn' for it.
But the error keeps popping up.

Could you please guide me where I have to enforce the correct lod, in more detail?

Thanks a lot!

**Comment by endink** [comment] 2023-11-09 10:52
@jossevessies Please post a new issue , the issue is solved.
